############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
  # Your block's GitHub URL (replace <USERNAME> and <COLLECTION-NAME> with your GitHub username and block collection name)
  - path: github.com/dr-maruf/hugo-blox-ripendil

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: hugo-blox/blox/community
    target: layouts/partials/blox/community/
    includeFiles: '**.html'
  - source: hugo-blox/blox/all-access
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    includeFiles: '**.css'
  - source: layouts
    target: layouts
  - source: assets
    target: assets
